# Generated by Django 4.2.1 on 2023-05-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_author_alter_product_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8, verbose_name='Просмотренные товары'),
        ),
    ]
