# Generated by Django 4.2.1 on 2023-05-31 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_recentlyviewed_delete_viewedproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentlyViewed',
        ),
    ]
