# Generated by Django 4.2 on 2023-05-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_coupon_order_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='contactnum',
            field=models.CharField(default='Номер Телефона', max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='userhome',
            field=models.CharField(default='Номер дома', max_length=10),
        ),
    ]
